# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: human_detection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'human_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15human_detection.proto\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"(\n\rImageResponse\x12\x17\n\x0fprocessed_image\x18\x01 \x01(\x0c\x32\x43\n\x0eHumanDetection\x12\x31\n\x0c\x44\x65tectHumans\x12\r.ImageRequest\x1a\x0e.ImageResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'human_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=25
  _globals['_IMAGEREQUEST']._serialized_end=59
  _globals['_IMAGERESPONSE']._serialized_start=61
  _globals['_IMAGERESPONSE']._serialized_end=101
  _globals['_HUMANDETECTION']._serialized_start=103
  _globals['_HUMANDETECTION']._serialized_end=170
# @@protoc_insertion_point(module_scope)
